name: Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set node version to 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install --frozen-lockfile
      - run: npm run deploy
        env:
          TOKEN_GITHUB: ${{secrets.TOKEN_GITHUB}}
